version: "3"
services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile-client
    ports:
      - "34008:4173"
    restart: unless-stopped
  server:
    build: .
    ports:
      - "34009:8080"
    restart: unless-stopped
